# -*- coding: utf-8 -*-
"""tugas1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFkREMfQqOLpqkx1np-0i_I81jojJi5p
"""

#variable

a = 2 # integer
hewan = "gajah" # String
#Untuk yang dasarnya tidak ada yang namanya char
b = 'A' # String
c = True # Boolean
d = False # Boolean
e = 2.0 # Float
f = [] # List / Array
g = {} # Dictionary
h = () # Tuple

print(b)
print(a)
print("Nama hewannya adalah: " + hewan)
print("Nama hewannya adalah: {}".format(a))
print("Nama: {}, Umur: {}".format("Aufa", 18))

Student_Name = ["Rizal", "Rayhan", "Resha", "Juven", "Aufa"]
print(Student_Name[0])
print(Student_Name[1])
print(Student_Name[2])
print(Student_Name[-2:])
Student_Name.append("dodo")
print(Student_Name)

List = ["A", "B", "C"]
print("ini huruf {}".format(List[0]))